.\"
.\" Copyright (c) 2003-2010 Alexandre Ratchov <alex@caoua.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd June 25, 2006
.Dt MIDISH 1
.Os
.Sh NAME
.Nm midish
.Nd MIDI sequencer and filter
.Sh SYNOPSIS
.Nm midish
.Op Fl bhv
.Sh DESCRIPTION
Midish is a MIDI sequencer/filter implemented as an interactive
command-line interpreter
(users wanting to use midish interactively may consider using the
.Xr rmidish 1
utility).
Here are some of its features:
.Pp
.Bl -bullet -compact
.It
Multiple MIDI devices handling
.It
Synchronisation to external MIDI devices
.It
Filtering/routing (controller mapping, keyboard splitting, ...)
.It
Track recording, editing, quantisation
.It
Import and export of standard MIDI files
.It
Tempo and time-signature changes, user configurable metronome
.It
System exclusive messages handling
.El
.Pp
The options are as follows:
.Bl -tag -width "-b "
.It Fl b
Do not process
.Pa "$HOME/.midishrc"
or
.Pa "/etc/midishrc"
and stop on the first error on the standard input.
Useful for scripting
.It Fl h
Print usage information.
.It Fl v
Print additionnal info before each line of input, useful to
front-ends and for dubugging.
.El
.Pp
Once midish started, the interpreter
processes the
.Pa "$HOME/.midishrc"
file (or
.Pa "/etc/midishrc"
if the latter doesn't exist)
and starts prompting for commands.
For further information about the syntax of
.Nm
refer to the
.Dq Midish user's manual .
.Sh FILES
.Bl -tag -width "$HOME/.midishrc" -compact
.It Pa "$HOME/.midishrc"
startup script
.It Pa "/etc/midishrc"
startup script (if
.Pa "$HOME/.midishrc"
doesn't exist)
.It Pa "/dev/rmidiN"
.Xr midi 4
devices used by
.Nm
.El
.Sh SEE ALSO
.Xr rmidish 1 ,
.Xr smfplay 1 ,
.Xr midiplay 1 ,
.Xr midi 4
.br
User's manual and tutorial
.br
http://caoua.org/midish/
