.\"
.\" Copyright (c) 2003-2010 Alexandre Ratchov <alex@caoua.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 22, 2005
.Dt RMIDISH 1
.Os
.Sh NAME
.Nm rmidish
.Nd front-end to
.Xr midish 1 ,
using the
.Xr readline 3
library
.Sh SYNOPSIS
.Nm rmidish
.Sh DESCRIPTION
The
.Nm
utility is a very simple front-end to
.Xr midish 1
that uses the
.Xr readline 3
library.
It runs
.Xr midish 1
in the background, issues an interactive prompt and
passes user commands to
.Xr midish 1 .
The initial purpose of
.Nm
was to illustrate how to use the
.Fl v
option of
.Xr midish 1
to create a front-end, but it can be run instead of
.Xr midish 1
to make the latter more user-friendly when used interactively.
.Sh SEE ALSO
.Xr midish 1 ,
.Xr readline 3
.br
Midish user's manual and tutorial
.br
http://caoua.org/midish/
.Sh BUGS
The
.Xr midish 1
executable has to be in the same directoy as
.Nm
