.\"
.\" Copyright (c) 2003-2005 Alexandre Ratchov
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without 
.\" modification, are permitted provided that the following conditions 
.\" are met:
.\"
.\" 	- Redistributions of source code must retain the above
.\" 	  copyright notice, this list of conditions and the
.\" 	  following disclaimer.
.\"
.\" 	- Redistributions in binary form must reproduce the above
.\" 	  copyright notice, this list of conditions and the
.\" 	  following disclaimer in the documentation and/or other
.\" 	  materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.Dd August 22, 2005
.Dt SMFPLAY 1
.Os
.Sh NAME
.Nm smfplay
.Nd play a standard MIDI file
.Sh SYNOPSIS
.Nm smfplay
.Op -mxy
.Op -d Ar devname
.Op -i Ar devname
midifile
.Sh DESCRIPTION
The 
.Nm 
utility plays a MIDI file. While playing, it can route events from one 
.Xr midi 4
device to another. To stop performance, send an interrupt signal to
.Nm
(for instance by pressing control ^C on the terminal).
The options are as follows:
.Bl -tag -width "-i devname "
.It Fl m
Use metronome. The metronome will follow tempo changes and time signature
changes in the midi file.
.It Fl x
Synchronise to an external 
.Xr midi 4
device. If the
.Fl i
flag is used then playback will be synchronised to the input device
else it will be synchronised to the default device.
.It Fl y
Send midi timing information to the default device. Useful if the
output device is a slave MIDI sequencer.
.It Fl d Ar filename
Default  
.Xr midi 4
device on which to play the midi file. If not specified, 
the content of the 
.Pa MIDIDEV
environment variable will be used instead.
.It Fl i Ar filename
Alternate input 
.Xr midi 4
device. Voice events (notes, controllers, etc) received on the input device
will be sent as-is to the default device. Without this flag, the default
device will be used for input.
.El
.Pp
The 
.Nm
utility is an interface to 
.Xr midish 1 .
If more specific features are needed, the user may consider using
.Xr midish 1 .
.Sh EXAMPLES
The following will play
.Pa mysong.mid
on device
.Pa /dev/rmidi4
and will use metronome.
.Bd -literal
smfplay -m -d /dev/rmidi4 mysong.mid
.Ed
.Sh SEE ALSO
.Xr smfrec 1 ,
.Xr midish 1 ,
.Xr midiplay 1 ,
.Xr midi 4

